baseURL: "https://kellner.team/"
theme: "up-business-theme"
languageCode: "de-at"

title: "kellner.team"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "kellner.team"
  description: "Mit WaiterRobot hast du die Möglichkeit, deine Bestellungsaufnahme digital zu erledigen. Egal ob sich um ein einmaliges Event oder dauerhafte Bewirtung handelt, WaiterRobot beschleunigt deinen Prozess im Servicebereich."
  images: 
    - "images/hero-image.png"

  logo: "assets0/logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "#"
    facebook: "#"

  location:
    - "Alexander Kauer, 2095 Drosendorf Altstadt"
    - "Dominik Dafert, 1100 Wien"

  contact:
    - "hallo@kellner.team"

  copyright: "© 2023 kellner.team"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2


taxonomies:
  series: "series"
  tags: "tags"


custom_css:
  - "css/custom.css"