baseURL: "https://kellner.team/"
theme: "up-business-theme"
languageCode: "de-at"

title: "kellner.team"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "kellner.team"
  description: "Mit WaiterRobot hast du die Möglichkeit, deine Bestellungsaufnahme digital zu erledigen."
  images: 
    - "images/hero-image.png"

  logo: "assets0/logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "#"
    facebook: "#"

  location:
    - "Alexander Kauer, 2095 Drosendorf Altstadt"
    - "Dominik Dafert, 1100 Wien"

  contact:
    - "hallo@kellner.team"

  copyright: "© 2023 kellner.team"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "Pricing"
      url: "/#"
      weight: 2

    - name: "Blog"
      url: "/blog"
      weight: 3

  buttons:
    - name: "Kontaktiere uns"
      url: "mailto:hallo@kellner.team"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Datenschutz"
      url: "/data-privacy"
      weight: 2


taxonomies:
  series: "series"
  tags: "tags"


custom_css:
  - "css/custom.css"